CREATE TABLE todo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '식별자',
    name VARCHAR(50) NOT NULL ,
    password VARCHAR(50) NOT NULL ,
    text VARCHAR(255) NOT NULL ,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at DATETIME NULL
)